{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "0b37f39b-244a-4cda-af70-816fa5dfd22e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.cluster import KMeans\n",
    "import joblib\n",
    "\n",
    "class DataAnalysisAgent:\n",
    "    def __init__(self):\n",
    "        self.data = None\n",
    "        self.summary = {}\n",
    "        \n",
    "    def load_data(self, file_path):\n",
    "        \"\"\"Load data from CSV, Excel, or other supported formats\"\"\"\n",
    "        try:\n",
    "            if file_path.endswith('.csv'):\n",
    "                self.data = pd.read_csv(file_path)\n",
    "            elif file_path.endswith(('.xls', '.xlsx')):\n",
    "                self.data = pd.read_excel(file_path)\n",
    "            elif file_path.endswith('.json'):\n",
    "                self.data = pd.read_json(file_path)\n",
    "            else:\n",
    "                raise ValueError(\"Unsupported file format\")\n",
    "            \n",
    "            print(f\"Data loaded successfully with {self.data.shape[0]} rows and {self.data.shape[1]} columns\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error loading data: {e}\")\n",
    "            return False\n",
    "    \n",
    "    def explore_data(self):\n",
    "        \"\"\"Generate basic exploratory analysis\"\"\"\n",
    "        if self.data is None:\n",
    "            print(\"No data loaded. Please load data first.\")\n",
    "            return None\n",
    "        \n",
    "        self.summary['shape'] = self.data.shape\n",
    "        self.summary['dtypes'] = self.data.dtypes\n",
    "        self.summary['missing'] = self.data.isnull().sum()\n",
    "        self.summary['numeric_summary'] = self.data.describe()\n",
    "        \n",
    "        # For categorical columns\n",
    "        cat_cols = self.data.select_dtypes(include=['object']).columns\n",
    "        if len(cat_cols) > 0:\n",
    "            self.summary['categorical_summary'] = {col: self.data[col].value_counts() for col in cat_cols}\n",
    "        \n",
    "        return self.summary\n",
    "    \n",
    "    def visualize_data(self, columns=None):\n",
    "        \"\"\"Create basic visualizations for the data\"\"\"\n",
    "        if self.data is None:\n",
    "            print(\"No data loaded. Please load data first.\")\n",
    "            return\n",
    "        \n",
    "        if columns is None:\n",
    "            numeric_cols = self.data.select_dtypes(include=['number']).columns[:5]  # Limit to first 5 columns\n",
    "        else:\n",
    "            numeric_cols = [col for col in columns if col in self.data.columns and pd.api.types.is_numeric_dtype(self.data[col])]\n",
    "        \n",
    "        # Distribution plots\n",
    "        plt.figure(figsize=(15, 10))\n",
    "        for i, col in enumerate(numeric_cols, 1):\n",
    "            plt.subplot(2, 3, i)\n",
    "            sns.histplot(self.data[col].dropna(), kde=True)\n",
    "            plt.title(f'Distribution of {col}')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "        \n",
    "        # Correlation heatmap\n",
    "        plt.figure(figsize=(10, 8))\n",
    "        corr_matrix = self.data[numeric_cols].corr()\n",
    "        sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')\n",
    "        plt.title('Correlation Matrix')\n",
    "        plt.show()\n",
    "    \n",
    "    def preprocess_data(self, handle_missing='mean', scale=True):\n",
    "        \"\"\"Preprocess the data for analysis\"\"\"\n",
    "        if self.data is None:\n",
    "            print(\"No data loaded. Please load data first.\")\n",
    "            return None\n",
    "        \n",
    "        # Create a copy to avoid modifying original data\n",
    "        processed_data = self.data.copy()\n",
    "        \n",
    "        # Handle missing values\n",
    "        numeric_cols = processed_data.select_dtypes(include=['number']).columns\n",
    "        if handle_missing == 'mean':\n",
    "            for col in numeric_cols:\n",
    "                processed_data[col].fillna(processed_data[col].mean(), inplace=True)\n",
    "        elif handle_missing == 'median':\n",
    "            for col in numeric_cols:\n",
    "                processed_data[col].fillna(processed_data[col].median(), inplace=True)\n",
    "        elif handle_missing == 'drop':\n",
    "            processed_data.dropna(inplace=True)\n",
    "        \n",
    "        # Scale numeric features\n",
    "        if scale:\n",
    "            scaler = StandardScaler()\n",
    "            processed_data[numeric_cols] = scaler.fit_transform(processed_data[numeric_cols])\n",
    "        \n",
    "        return processed_data\n",
    "    \n",
    "    def cluster_data(self, n_clusters=3, features=None):\n",
    "        \"\"\"Perform clustering on the data\"\"\"\n",
    "        if self.data is None:\n",
    "            print(\"No data loaded. Please load data first.\")\n",
    "            return None\n",
    "        \n",
    "        # Preprocess data\n",
    "        processed_data = self.preprocess_data()\n",
    "        \n",
    "        # Select features for clustering\n",
    "        if features is None:\n",
    "            features = processed_data.select_dtypes(include=['number']).columns\n",
    "        \n",
    "        # Apply PCA if there are many features\n",
    "        if len(features) > 10:\n",
    "            pca = PCA(n_components=10)\n",
    "            data_for_clustering = pca.fit_transform(processed_data[features])\n",
    "            print(f\"Applied PCA: Explained variance ratio: {sum(pca.explained_variance_ratio_):.2f}\")\n",
    "        else:\n",
    "            data_for_clustering = processed_data[features]\n",
    "        \n",
    "        # Apply KMeans clustering\n",
    "        kmeans = KMeans(n_clusters=n_clusters, random_state=42)\n",
    "        clusters = kmeans.fit_predict(data_for_clustering)\n",
    "        \n",
    "        # Add cluster labels to the original data\n",
    "        self.data['cluster'] = clusters\n",
    "        \n",
    "        # Visualize clusters (first 2 features or PCA components)\n",
    "        plt.figure(figsize=(10, 8))\n",
    "        if len(features) > 2:\n",
    "            pca_viz = PCA(n_components=2)\n",
    "            viz_data = pca_viz.fit_transform(processed_data[features])\n",
    "            plt.scatter(viz_data[:, 0], viz_data[:, 1], c=clusters, cmap='viridis')\n",
    "            plt.xlabel('PCA Component 1')\n",
    "            plt.ylabel('PCA Component 2')\n",
    "        else:\n",
    "            plt.scatter(processed_data[features[0]], processed_data[features[1]], c=clusters, cmap='viridis')\n",
    "            plt.xlabel(features[0])\n",
    "            plt.ylabel(features[1])\n",
    "        \n",
    "        plt.title(f'KMeans Clustering (k={n_clusters})')\n",
    "        plt.colorbar(label='Cluster')\n",
    "        plt.show()\n",
    "        \n",
    "        return clusters\n",
    "    \n",
    "    def save_model(self, model, filename):\n",
    "        \"\"\"Save a trained model\"\"\"\n",
    "        try:\n",
    "            joblib.dump(model, filename)\n",
    "            print(f\"Model saved to {filename}\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error saving model: {e}\")\n",
    "            return False\n",
    "    \n",
    "    def load_model(self, filename):\n",
    "        \"\"\"Load a trained model\"\"\"\n",
    "        try:\n",
    "            model = joblib.load(filename)\n",
    "            print(f\"Model loaded from {filename}\")\n",
    "            return model\n",
    "        except Exception as e:\n",
    "            print(f\"Error loading model: {e}\")\n",
    "            return None\n",
    "\n",
    "# Example usage\n",
    "if __name__ == \"__main__\":\n",
    "    agent = DataAnalysisAgent()\n",
    "    # Example: agent.load_data(\"your_data.csv\")\n",
    "    # agent.explore_data()\n",
    "    # agent.visualize_data()\n",
    "    # agent.cluster_data(n_clusters=4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "7c392e42-e7c7-4152-9142-c2545ea15539",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression, LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor\n",
    "from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report\n",
    "import joblib\n",
    "import datetime\n",
    "\n",
    "class AI_Data_Agent:\n",
    "    def __init__(self, workspace_dir='/Users/rajatbanne/Desktop/AI_Data_Agent'):\n",
    "        \"\"\"Initialize the AI Data Agent with a workspace directory\"\"\"\n",
    "        self.data = None\n",
    "        self.summary = {}\n",
    "        self.models = {}\n",
    "        self.workspace_dir = workspace_dir\n",
    "        self.results_dir = os.path.join(workspace_dir, 'results')\n",
    "        self.models_dir = os.path.join(workspace_dir, 'models')\n",
    "        self.reports_dir = os.path.join(workspace_dir, 'reports')\n",
    "        \n",
    "        # Create necessary directories if they don't exist\n",
    "        for directory in [self.workspace_dir, self.results_dir, self.models_dir, self.reports_dir]:\n",
    "            if not os.path.exists(directory):\n",
    "                os.makedirs(directory)\n",
    "                print(f\"Created directory: {directory}\")\n",
    "        \n",
    "        print(f\"AI Data Agent initialized in workspace: {self.workspace_dir}\")\n",
    "        \n",
    "    def load_data(self, file_path, sheet_name=None):\n",
    "        \"\"\"Load data from various file formats\"\"\"\n",
    "        try:\n",
    "            if file_path.endswith('.csv'):\n",
    "                self.data = pd.read_csv(file_path)\n",
    "            elif file_path.endswith(('.xls', '.xlsx')):\n",
    "                self.data = pd.read_excel(file_path, sheet_name=sheet_name)\n",
    "            elif file_path.endswith('.json'):\n",
    "                self.data = pd.read_json(file_path)\n",
    "            elif file_path.endswith('.parquet'):\n",
    "                self.data = pd.read_parquet(file_path)\n",
    "            elif file_path.endswith('.pickle') or file_path.endswith('.pkl'):\n",
    "                self.data = pd.read_pickle(file_path)\n",
    "            else:\n",
    "                raise ValueError(\"Unsupported file format. Supported formats: csv, xls, xlsx, json, parquet, pickle\")\n",
    "            \n",
    "            # Store the data source for reference\n",
    "            self.data_source = os.path.basename(file_path)\n",
    "            print(f\"Data loaded successfully from {self.data_source}\")\n",
    "            print(f\"Shape: {self.data.shape[0]} rows and {self.data.shape[1]} columns\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error loading data: {e}\")\n",
    "            return False\n",
    "    \n",
    "    def explore_data(self, save_report=True):\n",
    "        \"\"\"Generate comprehensive exploratory analysis\"\"\"\n",
    "        if self.data is None:\n",
    "            print(\"No data loaded. Please load data first.\")\n",
    "            return None\n",
    "        \n",
    "        # Basic information\n",
    "        self.summary['shape'] = self.data.shape\n",
    "        self.summary['columns'] = list(self.data.columns)\n",
    "        self.summary['dtypes'] = self.data.dtypes\n",
    "        self.summary['missing'] = self.data.isnull().sum()\n",
    "        self.summary['missing_percent'] = (self.data.isnull().sum() / len(self.data)) * 100\n",
    "        \n",
    "        # Numeric summary\n",
    "        numeric_cols = self.data.select_dtypes(include=['number']).columns\n",
    "        if len(numeric_cols) > 0:\n",
    "            self.summary['numeric_summary'] = self.data[numeric_cols].describe()\n",
    "            \n",
    "            # Check for outliers using IQR method\n",
    "            outliers = {}\n",
    "            for col in numeric_cols:\n",
    "                Q1 = self.data[col].quantile(0.25)\n",
    "                Q3 = self.data[col].quantile(0.75)\n",
    "                IQR = Q3 - Q1\n",
    "                outlier_count = ((self.data[col] < (Q1 - 1.5 * IQR)) | (self.data[col] > (Q3 + 1.5 * IQR))).sum()\n",
    "                outliers[col] = outlier_count\n",
    "            self.summary['outliers'] = outliers\n",
    "        \n",
    "        # Categorical summary\n",
    "        cat_cols = self.data.select_dtypes(include=['object', 'category']).columns\n",
    "        if len(cat_cols) > 0:\n",
    "            self.summary['categorical_summary'] = {col: self.data[col].value_counts().to_dict() for col in cat_cols}\n",
    "            self.summary['categorical_unique'] = {col: self.data[col].nunique() for col in cat_cols}\n",
    "        \n",
    "        # Save report if requested\n",
    "        if save_report:\n",
    "            timestamp = datetime.datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "            report_path = os.path.join(self.reports_dir, f\"data_exploration_{timestamp}.txt\")\n",
    "            \n",
    "            with open(report_path, 'w') as f:\n",
    "                f.write(f\"Data Exploration Report - {timestamp}\\n\")\n",
    "                f.write(f\"Data Source: {self.data_source if hasattr(self, 'data_source') else 'Unknown'}\\n\\n\")\n",
    "                \n",
    "                f.write(f\"Shape: {self.summary['shape']}\\n\\n\")\n",
    "                \n",
    "                f.write(\"Missing Values:\\n\")\n",
    "                missing_df = pd.DataFrame({\n",
    "                    'Count': self.summary['missing'],\n",
    "                    'Percent': self.summary['missing_percent']\n",
    "                })\n",
    "                f.write(f\"{missing_df.to_string()}\\n\\n\")\n",
    "                \n",
    "                if 'numeric_summary' in self.summary:\n",
    "                    f.write(\"Numeric Summary:\\n\")\n",
    "                    f.write(f\"{self.summary['numeric_summary'].to_string()}\\n\\n\")\n",
    "                \n",
    "                if 'outliers' in self.summary:\n",
    "                    f.write(\"Outliers (IQR method):\\n\")\n",
    "                    for col, count in self.summary['outliers'].items():\n",
    "                        f.write(f\"  {col}: {count} outliers\\n\")\n",
    "                    f.write(\"\\n\")\n",
    "                \n",
    "                if 'categorical_unique' in self.summary:\n",
    "                    f.write(\"Categorical Columns:\\n\")\n",
    "                    for col, unique in self.summary['categorical_unique'].items():\n",
    "                        f.write(f\"  {col}: {unique} unique values\\n\")\n",
    "                    f.write(\"\\n\")\n",
    "            \n",
    "            print(f\"Exploration report saved to {report_path}\")\n",
    "        \n",
    "        return self.summary\n",
    "    \n",
    "    def visualize_data(self, columns=None, save_plots=True):\n",
    "        \"\"\"Create visualizations for the data\"\"\"\n",
    "        if self.data is None:\n",
    "            print(\"No data loaded. Please load data first.\")\n",
    "            return\n",
    "        \n",
    "        timestamp = datetime.datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "        plots_dir = os.path.join(self.results_dir, f\"visualizations_{timestamp}\")\n",
    "        if save_plots and not os.path.exists(plots_dir):\n",
    "            os.makedirs(plots_dir)\n",
    "        \n",
    "        # Select columns to visualize\n",
    "        if columns is None:\n",
    "            numeric_cols = list(self.data.select_dtypes(include=['number']).columns)\n",
    "            if len(numeric_cols) > 10:  # Limit to first 10 columns if there are too many\n",
    "                numeric_cols = numeric_cols[:10]\n",
    "        else:\n",
    "            numeric_cols = [col for col in columns if col in self.data.columns and pd.api.types.is_numeric_dtype(self.data[col])]\n",
    "        \n",
    "        if not numeric_cols:\n",
    "            print(\"No numeric columns found for visualization.\")\n",
    "            return\n",
    "        \n",
    "        # 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67eb2104-4081-4710-8b01-0849cff3a697",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
